name: Generate docs and format

on: [push, pull_request_target]

jobs:
  postprocessing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: panvimdoc
        uses: kdheepak/panvimdoc@main
        with:
          vimdoc: nvim-texlabconfig
          pandoc: "README.md"
          version: "Neovim 0.7.0"

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "ci(docs): auto generate docs"
          branch: ${{ github.head_ref }}

      - name: "Format with Stylua"
        uses: JohnnyMorganz/stylua-action@1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: .

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "ci(format): format with stylua"
          branch: ${{ github.head_ref }}
